# -*- coding: utf-8 -*-

{
    'name': 'Formulier type PV projectform',
    'version': '14.0.1.0',
    'summary': '',
    'description': """
    """,
    'category': 'CRM',
    'author': 'Aardug, Arjan Rosman',
    'website': 'http://www.aardug.nl/',
    'depends': ['project_formulier',
                'project_formulier_quote',
                'formulier_quote_set_lines',
                'formulier_type_3',
            ],
    'data': [
            'data/data.xml',
            'views/access_assets.xml',
            'views/project_formulier_view.xml',
            'views/opportunity_formulier_template.xml',
            'views/quote_formulier_template.xml',
            'views/task_formulier_template.xml',
            'views/online_formulier_roof_select.xml',
            'views/roof_detail_one.xml',
            'views/roof_detail_two.xml',
            'views/roof_detail_three.xml',
            'views/roof_detail_four.xml',
            'views/roof_detail_five.xml',
            'views/roof_detail_six.xml',
            'views/roof_detail_seven.xml',
            'views/roof_detail_eight.xml',
            'views/online_formulier_panel_calculation.xml',
            'views/online_formulier_quote_template.xml',
            'views/tabs_template.xml',
        ],
    'installable': True,
    'application': False,
}
